name: "Azure App Configuration Sync"
description: "Azure App Configuration Sync of Properies using Azure CLI."
inputs:
  configurationFile:
    description: "Path to the configuration file in the repo, relative to the repo root. Also supports glob patterns and multiple files"
    required: true
  format:
    description: "Format of the configuration file. Valid values are: json, yaml, properties"
    required: true
  connectionString:
    description: "Connection string for the App Configuration instance"
    required: true
  separator:
    description: "Separator used when flattening the configuration file to key-value pairs (only for json and yaml format files)"
    required: false
  strict:
    description: "Specifies whether to use a strict sync which will make the App Configuration instance exactly match the configuration file (deleting key-values not in the configuration file). Defaults to false"
    required: false
  prefix:
    description: "Prefix that will be added to the front of the keys"
    required: false
  label:
    description: "Label to use when setting the key-value pairs. If not specified, a null label will be used"
    required: false
  depth:
    description: "Max depth (positive number) for flattening the configuration file"
    required: false
  tags:
    description: "Stringified form of a JSON object with the following shape: { [propertyName: string]: string; }"
    required: false
  contentType:
    description: "Content type for the values. Valid values are: 'keyvalue' (default) or 'keyvaultref'"
    required: false
    default: "keyvalue"

runs:
  using: "composite"
  steps:
    - name: Setup Script Path
      run: echo "SCRIPTS_DIR=${{ github.action_path }}/../scripts" >> $GITHUB_ENV
      shell: bash

    - name: Setup Script Args
      run: |
        echo "SCRIPTS_ARGS=\
        --configuration-file '${{ inputs.configurationFile }}' \
        --format '${{ inputs.format }}' \
        --connection-string '${{ inputs.connectionString }}' \
        --separator '${{ inputs.separator }}' \
        --strict '${{ inputs.strict }}' \
        --prefix '${{ inputs.prefix }}' \
        --label '${{ inputs.label }}' \
        --depth '${{ inputs.depth }}' \
        --tags '${{ inputs.tags }}' \
        --content-type '${{ inputs.contentType }}'" >> $GITHUB_ENV
      shell: bash

    - name: Validate Inputs
      run: ${{ env.SCRIPTS_DIR }}/sync-properties.sh --validate-inputs ${{ env.SCRIPTS_ARGS }}
      shell: bash

    - name: Import to App Configuration
      run: ${{ env.SCRIPTS_DIR }}/sync-properties.sh --perform-property-sync ${{ env.SCRIPTS_ARGS }}
      shell: bash
