name: "Azure App Configuration Sync"
description: "Azure App Configuration Sync of Properies and Feature Flags using Azure CLI."
inputs:
  configurationFile:
    description: "Path to the configuration file in the repo, relative to the repo root. Also supports glob patterns and multiple files"
    required: true
  connectionString:
    description: "Connection string for the App Configuration instance"
    required: true
  format:
    description: "Format of the configuration file. Valid values are: json, yaml, properties"
    required: true
  contentType:
    description: "Content type for the values. Valid values are: 'keyvalue' (default), 'keyvaultref' or 'featureflag'"
    required: false
    default: "keyvalue"
  label:
    description: "Label to use when setting the key-value pairs. If not specified, a null label will be used"
    required: false
    default: '\0'
  prefix:
    description: "Prefix that will be added to the front of the keys"
    required: false
  separator:
    default: "."
    description: "Separator used when flattening the configuration file to key-value pairs (only for json and yaml format files, defaults to '.')"
    required: false
  strict:
    description: "Specifies whether to use a strict sync which will make the App Configuration instance exactly match the configuration file (deleting key-values not in the configuration file). Defaults to false"
    required: false
  tags:
    description: "Stringified form of a JSON object with the following shape: { [propertyName: string]: string; }"
    required: false

outputs:
  changes_applied:
    description: "Indicates whether changes were applied during the sync process."
    value: ${{ steps.sync.outputs.changes_applied }}

runs:
  using: "composite"
  steps:
    - name: Setup Script and GitHub Path
      run: |
        echo "SCRIPTS_DIR=${{ github.action_path }}/../scripts" >> $GITHUB_ENV
        echo "${{ github.action_path }}/../scripts" >> $GITHUB_PATH
      shell: bash

    - name: Setup Script Args
      run: |
        echo "SCRIPTS_ARGS=\
        --configuration-file '${{ inputs.configurationFile }}' \
        --connection-string '${{ inputs.connectionString }}' \
        --format '${{ inputs.format }}' \
        --content-type '${{ inputs.contentType }}' \
        --label '${{ inputs.label }}' \
        --prefix '${{ inputs.prefix }}' \
        --separator '${{ inputs.separator }}' \
        --strict '${{ inputs.strict }}' \
        --tags '${{ inputs.tags }}'" >> $GITHUB_ENV
      shell: bash

    - name: Check Prerequisite Binaries
      run: |
        if [[ "${{ inputs.format }}" == "yaml" ]]; then
          check-dependencies.sh az jq yq
        else
          check-dependencies.sh az jq
        fi
      shell: bash

    - name: Validate Inputs
      run: sync-config.sh validate-inputs ${{ env.SCRIPTS_ARGS }}
      shell: bash

    - name: Sync with Azure App Configuration
      id: sync
      run: sync-config.sh execute ${{ env.SCRIPTS_ARGS }}
      shell: bash
